github.com:
    users:
        Redaration:
            oauth_token: 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
    git_protocol: https
    user: Redaration
    oauth_token: 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
